version: "3.9"

services:
  api:
    build: .
    container_name: fastapi-auth
    hostname: api
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - emqx
    networks:
      - red-auth  # ✅ misma red que los otros contenedores
    environment:
      - EMQX_API_BASE=http://emqx:8081/api/v4
      - EMQX_MANAGEMENT__DEFAULT_APPLICATION__USERNAME=admin
      - EMQX_MANAGEMENT__DEFAULT_APPLICATION__PASSWORD=admin123..

  mongo:
    image: mongo:5.0
    container_name: auth-mongo
    restart: always
    volumes:
      - auth-mongo-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - red-auth
  
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8082:8082"  
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    command: ["node", "app", "--port", "8082"]  
    depends_on:
      - mongo
    networks:
      - red-auth

  emqx:
    image: emqx/emqx:4.4.18
    container_name: emqx
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "8083:8083"
      - "18083:18083"
      - "8081:8081"
    environment:
      - EMQX_NAME=emqx
      - EMQX_ALLOW_ANONYMOUS=false
      - EMQX_LOADED_PLUGINS=emqx_management,emqx_dashboard,emqx_auth_mongo
      - EMQX_LOG__LEVEL=debug
      - EMQX_AUTH__MONGO__ENABLE=true
      - EMQX_AUTH__MONGO__SERVER=mongo:27017
      - EMQX_AUTH__MONGO__USERNAME=root
      - EMQX_AUTH__MONGO__PASSWORD=example
      - EMQX_AUTH__MONGO__DATABASE=iot
      - EMQX_AUTH__MONGO__AUTH_QUERY__COLLECTION=mqtt_user
      - EMQX_AUTH__MONGO__AUTH_QUERY__SELECTOR=username=%u
      - EMQX_AUTH__MONGO__AUTH_QUERY__PASSWORD_FIELD=password
      - EMQX_AUTH__MONGO__AUTH_QUERY__PASSWORD_HASH=bcrypt
      - EMQX_AUTH__MONGO__ACL_QUERY=on
      - EMQX_AUTH__MONGO__ACL_QUERY__DATABASE=iot
      - EMQX_AUTH__MONGO__ACL_QUERY__COLLECTION=mqtt_acl
      - EMQX_AUTH__MONGO__ACL_QUERY__SELECTOR=username=%u
      - EMQX_AUTH__MONGO__ACL_QUERY__TOPIC_FIELD=topic
      - EMQX_AUTH__MONGO__ACL_QUERY__CACHE_ENABLE=false
      - EMQX_AUTH__MONGO__ACL_QUERY__TOPIC_FUZZY=true
      - EMQX_DASHBOARD__DEFAULT_USER__PASSWORD=admin123..
      - EMQX_MANAGEMENT__DEFAULT_APPLICATION__SECRET=admin123..
    depends_on:
      - mongo
    networks:
      - red-auth
    volumes:
      - emqx-data:/opt/emqx/data
      - emqx-log:/opt/emqx/log

  frontend:
    build:
      context: ./FRONTEND_2.0
    container_name: frontend-app
    ports:
      - "3000:80"
    depends_on:
      - api
    networks:
      - red-auth

volumes:
  auth-mongo-data:
  emqx-data:
  emqx-log:

networks:
  red-auth:
    driver: bridge